<?php
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;

class AppController extends Controller
{
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler', [
            'enableBeforeRedirect' => false,
        ]);
        $this->loadComponent('Flash');
    }

    public function beforeFilter(Event $event)
    {
        $this->viewBuilder()->theme('Site'); // AppUI is my plugin name

        $this->loadModel('Menu');
        $menu = $this->Menu->find('all', ['contain'=>[
          'ChildMenu'=>[
            'conditions'=>['ChildMenu.status'=>1]
          ]
        ],
        'conditions'=>[
          'parent_id' => 0,
          'Menu.status'=>1
          ]]);
        $menu = $menu->all();
        $this->set('menu', $menu);

        $this->loadModel('Configs');
        $footer_presentation = $this->Configs->find('all',['conditions'=>['slug'=>'footer-presentation']])->first();
        $this->set(compact('footer_presentation'));

        $full_footer = $this->Configs->find('all',['conditions'=>['slug'=>'full-footer']])->first();
        $this->set(compact('full_footer'));

        $top_signin = $this->Configs->find('all',['conditions'=>['slug'=>'top-signin']])->first();
        $this->set(compact('top_signin'));

        $top_ouvidoria = $this->Configs->find('all',['conditions'=>['slug'=>'top-ouvidoria']])->first();
        $this->set(compact('top_ouvidoria'));

        $servicos_list = [""=>"Tipo de Serviço","CONSULTORIOS / CLINICAS ESPECIALIZADAS / POLICLINICAS"=>"CONSULTORIOS / CLINICAS ESPECIALIZADAS / POLICLINICAS","HOME CARE"=>"HOME CARE","HOSPITAL ESPECIALIZADO"=>"HOSPITAL ESPECIALIZADO","HOSPITAL GERAL"=>"HOSPITAL GERAL","LABORATORIO"=>"LABORATORIO","PRONTO-SOCORRO ESPECIALIZADO"=>"PRONTO-SOCORRO ESPECIALIZADO","PRONTO-SOCORRO GERAL"=>"PRONTO-SOCORRO GERAL","SERVIÇO DIAGNOSE  E TRATAMENTO"=>"SERVIÇO DIAGNOSE  E TRATAMENTO"];
        $especialidades_list = [""=>"Especialidade", "ACUPUNTURA"=>"ACUPUNTURA", "ALERGOLOGIA E IMUNOLOGIA"=>"ALERGOLOGIA E IMUNOLOGIA", "ANATOMIA PATOLOGICA E CITOPATOLOGIA"=>"ANATOMIA PATOLOGICA E CITOPATOLOGIA", "ANGIOLOGIA"=>"ANGIOLOGIA", "ANGIORESSONANCIA"=>"ANGIORESSONANCIA", "ANGIOTOMOGRAFIA"=>"ANGIOTOMOGRAFIA", "AUDIOMETRIA"=>"AUDIOMETRIA", "AUDIOMETRIA/IMPEDANCIOMETRIA"=>"AUDIOMETRIA/IMPEDANCIOMETRIA", "BRONCOSCOPIA"=>"BRONCOSCOPIA", "CARDIOLOGIA"=>"CARDIOLOGIA", "CARDIOLOGIA PEDIATRICA"=>"CARDIOLOGIA PEDIATRICA", "CARDIOTOCOGRAFIA"=>"CARDIOTOCOGRAFIA", "CIRURGIA BUCO-MAXILO-FACIAL"=>"CIRURGIA BUCO-MAXILO-FACIAL", "CIRURGIA CARDIACA"=>"CIRURGIA CARDIACA", "CIRURGIA DE CABEÇA E PESCOÇO"=>"CIRURGIA DE CABEÇA E PESCOÇO", "CIRURGIA DE MAO"=>"CIRURGIA DE MAO", "CIRURGIA GERAL"=>"CIRURGIA GERAL", "CIRURGIA ONCOLÓGICA"=>"CIRURGIA ONCOLÓGICA", "CIRURGIA PEDIATRICA"=>"CIRURGIA PEDIATRICA", "CIRURGIA PLASTICA REPARADORA"=>"CIRURGIA PLASTICA REPARADORA", "CIRURGIA TORACICA"=>"CIRURGIA TORACICA", "CIRURGIA VASCULAR"=>"CIRURGIA VASCULAR", "CLINICA MEDICA"=>"CLINICA MEDICA", "COLONOSCOPIA"=>"COLONOSCOPIA", "COLPOSCOPIA"=>"COLPOSCOPIA", "CORE BIOPSIA"=>"CORE BIOPSIA", "DENSITOMETRIA OSSEA"=>"DENSITOMETRIA OSSEA", "DERMATOLOGIA CLINICO-CIRURGICA"=>"DERMATOLOGIA CLINICO-CIRURGICA", "DERMATOLOGIA PEDIÁTRICA"=>"DERMATOLOGIA PEDIÁTRICA", "DOPPLERFLUXOMETRIA"=>"DOPPLERFLUXOMETRIA", "ECOCARDIOGRAMA"=>"ECOCARDIOGRAMA", "ELASTOGRAFIA HEPATICA"=>"ELASTOGRAFIA HEPATICA", "ELETROCARDIOGRAMA - ECG"=>"ELETROCARDIOGRAMA - ECG", "ELETROENCEFALOGRAMA"=>"ELETROENCEFALOGRAMA", "ELETRONEUROMIOGRAFIA"=>"ELETRONEUROMIOGRAFIA", "ENDOCRINOLOGIA E METABOLOGIA"=>"ENDOCRINOLOGIA E METABOLOGIA", "ENDOSCOPIA  RESPIRATORIA / BRONCOSCOPIA"=>"ENDOSCOPIA  RESPIRATORIA / BRONCOSCOPIA", "ENDOSCOPIA DIGESTIVA"=>"ENDOSCOPIA DIGESTIVA", "ERGOMETRIA"=>"ERGOMETRIA", "ESOFAGOMETRIA"=>"ESOFAGOMETRIA", "FISIATRIA"=>"FISIATRIA", "FISIOTERAPIA MOTORA"=>"FISIOTERAPIA MOTORA", "FISIOTERAPIA RESPIRATORIA"=>"FISIOTERAPIA RESPIRATORIA", "FONOAUDIOLOGIA E FONIATRIA"=>"FONOAUDIOLOGIA E FONIATRIA", "GASTROENTEROLOGIA"=>"GASTROENTEROLOGIA", "GENETICA CLINICA"=>"GENETICA CLINICA", "GERAL"=>"GERAL", "GERIATRIA"=>"GERIATRIA", "GINECOLOGIA"=>"GINECOLOGIA", "HEMATOLOGIA"=>"HEMATOLOGIA", "HEMODIALISE / DIALISE PERITONEAL"=>"HEMODIALISE / DIALISE PERITONEAL", "HEMODINAMICA"=>"HEMODINAMICA", "HEPATOLOGIA"=>"HEPATOLOGIA", "HISTEROSCOPIA DIAGNOSTICA E CIRURGICA"=>"HISTEROSCOPIA DIAGNOSTICA E CIRURGICA", "HOLTER"=>"HOLTER", "HOMEOPATIA"=>"HOMEOPATIA", "IMPEDANCIOMETRIA"=>"IMPEDANCIOMETRIA", "INFECTOLOGIA"=>"INFECTOLOGIA", "LITOTRIPSIA"=>"LITOTRIPSIA", "MAMOGRAFIA"=>"MAMOGRAFIA", "MAMOTOMIA"=>"MAMOTOMIA", "MAPA- MAPEAMENTO DE PRESSAO ARTERIAL"=>"MAPA- MAPEAMENTO DE PRESSAO ARTERIAL", "MAPEAMENTO CEREBRAL"=>"MAPEAMENTO CEREBRAL", "MASTOLOGIA"=>"MASTOLOGIA", "MEDICINA NUCLEAR"=>"MEDICINA NUCLEAR", "NEFROLOGIA"=>"NEFROLOGIA", "NEUROCIRURGIA"=>"NEUROCIRURGIA", "NEUROLOGIA"=>"NEUROLOGIA", "NEUROLOGIA PEDIATRICA"=>"NEUROLOGIA PEDIATRICA", "NUTRICIONISTA"=>"NUTRICIONISTA", "OBSTETRICIA"=>"OBSTETRICIA", "OFTALMOLOGIA"=>"OFTALMOLOGIA", "ONCOLOGIA"=>"ONCOLOGIA", "ORTOPEDIA E TRAUMATOLOGIA"=>"ORTOPEDIA E TRAUMATOLOGIA", "OTORRINOLARINGOLOGIA"=>"OTORRINOLARINGOLOGIA", "OXIGENOTERAPIA HIPERBARICA"=>"OXIGENOTERAPIA HIPERBARICA", "PATOLOGIA CLINICA"=>"PATOLOGIA CLINICA", "PEDIATRIA"=>"PEDIATRIA", "PNEUMOLOGIA"=>"PNEUMOLOGIA", "PNEUMOLOGIA PEDIATRICA"=>"PNEUMOLOGIA PEDIATRICA", "POLISSONOGRAFIA"=>"POLISSONOGRAFIA", "POTENCIAL EVOCADO"=>"POTENCIAL EVOCADO", "PROCTOLOGIA"=>"PROCTOLOGIA", "PROVA DE FUNÇAO PULMONAR"=>"PROVA DE FUNÇAO PULMONAR", "PSICOLOGIA"=>"PSICOLOGIA", "PSIQUIATRIA"=>"PSIQUIATRIA", "QUIMIOTERAPIA"=>"QUIMIOTERAPIA", "RADIOLOGIA"=>"RADIOLOGIA", "RADIOTERAPIA"=>"RADIOTERAPIA", "RESSONANCIA MAGNETICA NUCLEAR"=>"RESSONANCIA MAGNETICA NUCLEAR", "RETOSSIGMOIDOSCOPIA"=>"RETOSSIGMOIDOSCOPIA", "REUMATOLOGIA"=>"REUMATOLOGIA", "TOMOGRAFIA COMPUTADORIZADA"=>"TOMOGRAFIA COMPUTADORIZADA", "ULTRASSONOGRAFIA"=>"ULTRASSONOGRAFIA", "ULTRASSONOGRAFIA OCULAR"=>"ULTRASSONOGRAFIA OCULAR", "URODINAMICA COMPLETA"=>"URODINAMICA COMPLETA", "UROLOGIA"=>"UROLOGIA"];
        $cidades_list = [""=>"Município", "ANGRA DOS REIS"=>"ANGRA DOS REIS", "ARARUAMA"=>"ARARUAMA", "AREAL"=>"AREAL", "ARRAIAL DO CABO"=>"ARRAIAL DO CABO", "BARRA DO PIRAI"=>"BARRA DO PIRAI", "BARRA MANSA"=>"BARRA MANSA", "BELFORD ROXO"=>"BELFORD ROXO", "BOM JARDIM"=>"BOM JARDIM", "BOM JESUS DO ITABAPOANA"=>"BOM JESUS DO ITABAPOANA", "CABO FRIO"=>"CABO FRIO", "CACHOEIRAS DE MACACU"=>"CACHOEIRAS DE MACACU", "CAMBUCI"=>"CAMBUCI", "CAMPOS DOS GOYTACAZES"=>"CAMPOS DOS GOYTACAZES", "CANTAGALO"=>"CANTAGALO", "CARDOSO MOREIRA"=>"CARDOSO MOREIRA", "CASIMIRO DE ABREU"=>"CASIMIRO DE ABREU", "CORDEIRO"=>"CORDEIRO", "DUQUE DE CAXIAS"=>"DUQUE DE CAXIAS", "IGUABA GRANDE"=>"IGUABA GRANDE", "ITABORAI"=>"ITABORAI", "ITAGUAI"=>"ITAGUAI", "ITALVA"=>"ITALVA", "ITAOCARA"=>"ITAOCARA", "ITAPERUNA"=>"ITAPERUNA", "LAJE DO MURIAE"=>"LAJE DO MURIAE", "MACAE"=>"MACAE", "MACUCO"=>"MACUCO", "MAGE"=>"MAGE", "MARICA"=>"MARICA", "MENDES"=>"MENDES", "MESQUITA"=>"MESQUITA", "MIGUEL PEREIRA"=>"MIGUEL PEREIRA", "MIRACEMA"=>"MIRACEMA", "NATIVIDADE"=>"NATIVIDADE", "NILOPOLIS"=>"NILOPOLIS", "NITEROI"=>"NITEROI", "NOVA FRIBURGO"=>"NOVA FRIBURGO", "NOVA IGUACU"=>"NOVA IGUACU", "PARACAMBI"=>"PARACAMBI", "PARAIBA DO SUL"=>"PARAIBA DO SUL", "PATY DO ALFERES"=>"PATY DO ALFERES", "PETROPOLIS"=>"PETROPOLIS", "PINHEIRAL"=>"PINHEIRAL", "PIRAI"=>"PIRAI", "PORCIUNCULA"=>"PORCIUNCULA", "QUEIMADOS"=>"QUEIMADOS", "RESENDE"=>"RESENDE", "RIO BONITO"=>"RIO BONITO", "RIO CLARO"=>"RIO CLARO", "RIO DAS OSTRAS"=>"RIO DAS OSTRAS", "RIO DE JANEIRO"=>"RIO DE JANEIRO", "SANTO ANTONIO DE PADUA"=>"SANTO ANTONIO DE PADUA", "SAO FIDELIS"=>"SAO FIDELIS", "SAO FRANCISCO DE ITABAPOANA"=>"SAO FRANCISCO DE ITABAPOANA", "SAO GONCALO"=>"SAO GONCALO", "SAO JOAO DE MERITI"=>"SAO JOAO DE MERITI", "SAO PEDRO DA ALDEIA"=>"SAO PEDRO DA ALDEIA", "SAO SEBASTIAO DO ALTO"=>"SAO SEBASTIAO DO ALTO", "SAQUAREMA"=>"SAQUAREMA", "SEROPEDICA"=>"SEROPEDICA", "TERESOPOLIS"=>"TERESOPOLIS", "TRES RIOS"=>"TRES RIOS", "VASSOURAS"=>"VASSOURAS", "VOLTA REDONDA"=>"VOLTA REDONDA"];
        $this->set(compact('servicos_list', 'especialidades_list', 'cidades_list'));
    }
}
